Access logs: handle possibly undefined source object
CleverCloud/clever-tools pull request #440
Opened 2020-11-03 00:26 UTC by BlackYoup

Fix #399

After this fix, if the source object isn't defined, the log will appear as:
```
2020-11-02T16:31:36.512Z [ 10.2.204.148 ] GET console.clever-cloud.com /ping 304
```

I removed the localization part entirely because the `-` symbol is used as a delimiter in the extended format, not as a missing data symbol like it is in the CLF format.

I don't know if the extended log is meant to be parsed. If it is, how can we replace the source field? Using a `unknown` placeholder text? Or `missing`?

2021-02-08 14:45 UTC, hsablonniere requested changes

2021-02-08 14:45 UTC, hsablonniere commented on src/models/accesslogs.js
> +  if (l.s) {
```js
  if (l.s != null)
```

2021-02-08 14:46 UTC, hsablonniere commented
@BlackYoup I don't think it's meant to be parsed. I'm ok with just removing it like you did.

2021-02-08 17:26 UTC, BlackYoup commented on src/models/accesslogs.js
> +  if (l.s) {
updated

2021-02-09 09:42 UTC, hsablonniere commented
@BlackYoup Thanks :wink:

2021-02-09 09:42 UTC, merged