feat(deploy): add same-commit-policy option
CleverCloud/clever-tools pull request #598
Opened 2023-08-29 13:29 UTC by aurrelhebert

Closes #276

2023-08-29 13:41 UTC, hsablonniere commented
LGTM, I just need to do some QA and we'll be able to merge this ;-)

2024-01-19 10:00 UTC, miton18 commented
can you add a new line ?

```
``
[ERROR] The clever-cloud application is up-to-date (7a8c944350ead07842ff95162f230dbda747dd74). You can set a policy with 'same-commit-policy' to handle differently when remote HEAD has the same commit as the one to push. Or try this command to restart the application:
        clever restart
`

2024-01-19 10:03 UTC, hsablonniere requested changes

2024-01-19 10:04 UTC, miton18 commented on src/command-options.js
> +        : cliparse.parsers.error('The output policy must be one of ' + availablePolicies.join(', '));
```suggestion
        : cliparse.parsers.error('The output policy must be one of  ${availablePolicies.join(', ')});
```

2024-01-19 10:06 UTC, miton18 commented on src/command-options.js
> +    description: `Which policy to apply when the same commit is the same as the remote one. Availabe policies are (${availablePolicies.join(', ')})`,
```suggestion
    description: `Which policy to apply when the local commit is the same as the remote one. Available policies are (${availablePolicies.join(', ')})`,
```

2024-01-19 10:45 UTC, miton18 approved these changes

2024-01-19 10:47 UTC, hsablonniere approved these changes
Well done @aurrelhebert :+1: :clap:

2024-01-19 10:47 UTC, merged