feat(addon): enable materia kv
CleverCloud/clever-tools pull request #706
Opened 2024-03-27 15:11 UTC by aurrelhebert

2024-03-27 17:48 UTC, hsablonniere commented
It would be nice to find a way not to have a default plan.

2024-03-27 17:52 UTC, hsablonniere commented
![image](https://github.com/CleverCloud/clever-tools/assets/236342/b480a127-a19a-450e-b95d-80668f067812)

* I would add an empty line after `Name:` and before the warning
* I would spell it `MateriaDB KV` instead of `materia kv` in the warning
* I would use yellow for the warning and another color (green or blue) for the commands
* Maybe add an ascii warning before the message like this `/!\`

Apart from those details, well done @aurrelhebert

2024-03-27 17:57 UTC, hsablonniere requested changes
I added a suggestion and other comments are above.

2024-03-27 17:57 UTC, hsablonniere commented on src/commands/addon.js
> +      }
suggestion: sometimes I use an array + join to simplify multiline messages

```js
if (providerName === 'kv') {
  const materiaMessage = [
    `The materia ${providerName} provider is currently available in alpha, consider using it with care`,
    'To use the redis-cli command exec:',
    colors.yellow(`source <(clever addon env ${addon.id} -F shell)`),
    colors.yellow('redis-cli -h $KV_HOST -p $KV_PORT'),
  ].join('\n');
  Logger.println(materia);
}
```

2024-04-03 12:48 UTC, hsablonniere approved these changes
LGTM :+1: 

TODO: fixup both commits into one

2024-04-05 11:38 UTC, davlgd requested changes
LGTM, just some text nitpicks/sync with Console

2024-04-05 11:38 UTC, davlgd commented on src/commands/addon.js
> +        ? { ...jsonAddon, availability: 'alpha', warning: 'Consider using it with care' }
```suggestion
        ? { ...jsonAddon, availability: 'alpha', warning: 'Don't store sensitive or production grade data' }
```

2024-04-05 11:38 UTC, davlgd commented on src/commands/addon.js
> +          colors.yellow(`/!\\ The MateriaDB ${providerName.toUpperCase()} provider is currently available in alpha, consider using it with care`),
```suggestion
          colors.yellow(`/!\\ MateriaDB ${providerName.toUpperCase()} is in Alpha testing phase, don't store sensitive or production grade data`),
```

2024-04-05 11:38 UTC, davlgd commented on src/commands/addon.js
> +          colors.yellow(`/!\\ The MateriaDB ${providerName.toUpperCase()} provider is currently available in alpha, consider using it with care`),
`/!\` or ⚠️ ? :D

2024-04-05 11:38 UTC, davlgd commented on src/commands/addon.js
> +          'To use the redis-cli command exec:',
```suggestion
          "You can easily use MateriaDB KV with 'redis-cli', with such commands:",
```

2024-04-05 15:10 UTC, davlgd approved these changes
LGTM, Good team work! 💡☁️🚀

2024-04-05 15:16 UTC, merged