feat(activity): add deployment id
CleverCloud/clever-tools pull request #724
Opened 2024-04-16 16:03 UTC by pdesoyres-cc

Fixes #430
Fixes #193

This PR displays the deployment id in the output table.

Before:

```
2024-04-16T13:02:20+02:00  OK           DEPLOY     af81a57abe99c43a47527ddfdda9a12833189d88  Git
2024-04-16T13:22:44+02:00  OK           DEPLOY     fa491d14d320a9acf70fb7fb7482959ea527e5fa  Git
2024-04-16T13:33:02+02:00  OK           DEPLOY     7fe5c8b4cbdccf4e763f2eb4b798bc5c442e659b  Git
```

After:

```
2024-04-16T13:02:20+02:00  deployment_6c931b46-0275-4935-8f1d-04b4d26f878a  OK           DEPLOY     af81a57abe99c43a47527ddfdda9a12833189d88  Git
2024-04-16T13:22:44+02:00  deployment_bf87aed5-f95e-4936-bcd7-f13bacf23491  OK           DEPLOY     fa491d14d320a9acf70fb7fb7482959ea527e5fa  Git
2024-04-16T13:33:02+02:00  deployment_b1f77ac7-2fec-4b5a-b1b2-5981a84575e0  OK           DEPLOY     7fe5c8b4cbdccf4e763f2eb4b798bc5c442e659b  Git
```

2024-04-25 09:31 UTC, aurrelhebert approved these changes
QA OK! Thanks

2024-05-22 16:26 UTC, hsablonniere requested changes
Really nice @pdesoyres-cc, thank you :+1:

I tried the built version :wink:

I think it's a bit too large now. Can we update the git SHA1 (in another commit) to have a short version (8 chars).

2024-05-23 12:09 UTC, hsablonniere commented on src/commands/activity.js
> +      event.commit ? event.commit.substring(0, 8) : 'N/A',
nitpick: what about this?

```js
event?.commit?.substring(0, 8) ?? 'N/A',
```

2024-05-23 12:40 UTC, miton18 approved these changes

2024-05-23 12:50 UTC, hsablonniere approved these changes

2024-05-23 12:51 UTC, merged