feat(parsers): add a parser to parse boolean with a default value true
CleverCloud/clever-tools pull request #749
Opened 2024-05-28 08:41 UTC by aurrelhebert

2024-06-13 15:28 UTC, pdesoyres-cc requested changes
LGTM with just a little comment

2024-06-13 15:28 UTC, pdesoyres-cc commented on src/parsers.js
> + * @returns {bool} true or false
`{bool}` type doesn't exist. you should use `{boolean}` instead.

2024-06-26 08:48 UTC, miton18 commented
Do we need a bool parser ?

2024-06-26 13:07 UTC, aurrelhebert commented
Closing as related to the `watch` param we decided not to support

2024-06-26 13:07 UTC, closed without merging