feat(stop): allow to also cancel any ongoing deployment
CleverCloud/clever-tools pull request #766
Opened 2024-06-24 20:40 UTC by davlgd

This PR adds `--cancel` and `-c` to the `stop` command. It allows to ask to stop the app and to cancel any ongoing deployment with only one command.

The branch has been rebased on `support-app-id` from Pierre

2024-06-26 14:02 UTC, hsablonniere reviewed
:+1: I'm OK with the code but I want to discuss the UX...

* a `clever stop --cancel` fails if there is no ongoing deployment
* why no `clever stop && clever cancel-deploy`?
* is `--cancel` clear enough? should it be `clever stop --cancel-deploy`?

2024-06-26 16:25 UTC, davlgd commented
> 👍 I'm OK with the code but I want to discuss the UX...
> 
> * a `clever stop --cancel` with fail if there is no ongoing deployment
> * why no `clever stop && clever cancel-deploy`?
> * is `--cancel` clear enough? should it be `clever stop --cancel-deploy`?

A `clever stop && clever cancel-deploy` is what I try to avoid here. And I'm often in the case where I want to stop every deployment of an app, it's why I did this at first. 

For the flag name I'm open. Help is clear enough but the command is `cancel-deploy`. We can also use a more generic `--force` for example.

2024-06-27 16:58 UTC, davlgd commented
As discussed in sync it's now: 
* `--all` flag
* Don't `cancel-deploy` if there is no ongoing deployment, without throwing an error
* Rebased on master

2024-06-28 07:37 UTC, aurrelhebert approved these changes
LGTM! Looks clean to me

2024-07-01 16:14 UTC, hsablonniere requested changes
I don't think a command should import another command. I'll rework the commit myself.

2024-07-01 17:08 UTC, hsablonniere requested changes
I updated the code so a command does not rely on another but I'm not sure this update is necessary.

From my tests, a stop on an app cancels any ongoing deployments (new commits and upscaling). Let's do some more tests before merging this...

2025-05-13 16:39 UTC, closed without merging