docs(addon): better manage alpha/beta providers
CleverCloud/clever-tools pull request #778
Opened 2024-06-26 17:45 UTC by davlgd

Prepare Alpha public access for Keycloak, better manage Alpha/Beta message after an add-on creation. One is added for Pulsar.

2024-06-27 16:19 UTC, hsablonniere requested changes

2024-06-27 16:28 UTC, davlgd commented on src/commands/addon.js
> +  const wipProviders = { keycloak: keycloak, kv: kv, 'addon-pulsar': pulsar };
As discussed in sync, I'll directly declare the whole object.

2024-06-27 16:31 UTC, davlgd commented on src/commands/addon.js
> +  const wipProviders = { keycloak: keycloak, kv: kv, 'addon-pulsar': pulsar };
As discussed, I need some variables (`addon.id` for example) to build this object, so I can't just move it. I prefer to let it there if it's ok for you.

2024-06-28 07:33 UTC, aurrelhebert approved these changes

2024-07-01 13:58 UTC, hsablonniere commented on src/commands/addon.js
> +  const wipProviders = { keycloak: keycloak, kv: kv, 'addon-pulsar': pulsar };
OK, let's go like this for now :+1:

2024-07-01 14:05 UTC, hsablonniere approved these changes
LGTM :+1:

2024-07-01 14:05 UTC, merged