[PoC] Network Groups initial support
CleverCloud/clever-tools pull request #780
Opened 2024-06-27 14:50 UTC by davlgd

⚠️ This is an experimental project to support Network groups ⚠️

2025-01-30 14:29 UTC, pdesoyres-cc requested changes
Well done David. I've seen some bugs and little improvments here and there.

I've raised the following:

* we may need to improve doc:
  * maybe we could have a diagram showing 2 apps and 1 addon talking together and what's the difference between "with NG" and "without NG".
  * we don't know what to do with the domain name.
  * we don't have the receipe for adding an external peer and how to add it to the Wireguard. Even if we plan to ease this part with a deamon, I think we should add such a doc.
* we can only add app or addon from our personal organization (`checkMembersToLink` only looks into personal org).
* we need to think about: does a ng bound to org A can link app from or B ?
* the `ng get-config` command does not work on a `CleverPeer`

2025-01-30 15:47 UTC, davlgd commented
> Well done David. I've seen some bugs and little improvments here and there.
> 
> I've raised the following:
> 
> * we may need to improve doc:
>   
>   * maybe we could have a diagram showing 2 apps and 1 addon talking together and what's the difference between "with NG" and "without NG".
>   * we don't know what to do with the domain name.
>   * we don't have the receipe for adding an external peer and how to add it to the Wireguard. Even if we plan to ease this part with a deamon, I think we should add such a doc.
> * we can only add app or addon from our personal organization (`checkMembersToLink` only looks into personal org).
> * we need to think about: does a ng bound to org A can link app from or B ?
> * the `ng get-config` command does not work on a `CleverPeer`

Thanks for the review. Part of this will be covered by CC documentation and refined CT documentation/links to demos. I'll add this prior to release.

2025-01-31 13:00 UTC, pdesoyres-cc approved these changes

2025-02-26 18:05 UTC, hsablonniere requested changes
Amazing work @davlgd !!!! :clap: well done

I created a few comments and I also have local notes. We'll figure out the details in tomorrow's meeting.

2025-02-26 18:21 UTC, davlgd commented on docs/ng.md
> +- XXX
I'll add it once everything is ready for prime time

2025-02-27 10:00 UTC, pdesoyres-cc commented on src/models/ng.js
> +    async function pollOnce () {
here:

```js
/**
 * This class handles Polling process.
 * It doesn't really run a callback at a certain rate.
 * Instead, after each polling tick, it waits for a given delay before doing a new tick.
 * This way, the callback can take more time than the delay, it's not going to stack the processes.
 *
 * Also, good care is taken of the stopping process: It ensures that the polling process really stops even if the
 * stop command is called while the callback is running or while the timer is waiting for the nex tick.
 */
export class Polling {
  /**
   *
   * @param {() => Promise<any>} asyncCallback The function to be called at each polling tick.
   * @param {number} delay The delay to wait after each polling tick (in milliseconds).
   */
  constructor (asyncCallback, delay) {
    this._asyncCallback = asyncCallback;
    this._delay = delay;
    this._running = false;
    this._timer = new SingleTimer();
  }

  /**
   * @return {boolean} Whether the polling process is running
   */
  get running() {
    return this._running;
  }

  /**
   * Starts the polling process. If it was already running, we force stopping it before.
   * @return {Promise<void>}
   */
  start() {
    // force stop before starting
    this.stop();

    this._running = true;
    return this._tick();
  }

  /**
   * Stops the polling process.
   */
  stop() {
    this._running = false;
    this._timer.clear();
  }

  _tick() {
    // do nothing if not running
    if (!this.running) {
      return Promise.resolve();
    }
    return this._asyncCallback()
      .finally(() => {
        // program the next tick only if still running
        if (this.running) {
          this._timer.set(() => this._tick(), this._delay);
        }
      })
  }
}

/**
 * This class is a wrapper around `setTimeout` and `clearTimeout` native functions.
 * It ensures that only one timer is running at a time.
 * If one trys to start a new one, it ensures that the running one is stopped before.
 */
class SingleTimer {

  constructor () {
    this._id = null;
  }

  /**
   * @return {string|null} The id of the running timer. `null` if none is running.
   */
  get id() {
    return this._id;
  }

  /**
   * Starts a timer using `setTimeout` native function.
   *
   * It forces the running one to be stopped before starting.
   *
   * @param {() => any} callback The function to call when the timer elapses.
   * @param [delay=1] The number of milliseconds to wait before calling the `callback`.
   * @param args Optional arguments to pass when the `callback` is called.
   * @return {string}
   */
  set(callback, delay, ...args) {
    // force stopping current timeout if any
    this.clear();

    this._id = setTimeout(callback, delay, args);
    return this._id;
  }

  /**
   * Stops the current running timer.
   */
  clear() {
    if (this._id != null) {
      clearTimeout(this._id);
      this._id = null;
    }
  }
}
```

2025-02-27 13:51 UTC, miton18 submitted a review, later dismissed

2025-03-06 18:57 UTC, merged