foo
CleverCloud/clever-tools pull request #809
Opened 2024-07-25 15:26 UTC by hsablonniere

2024-10-14 07:36 UTC, miton18 requested changes

2024-10-14 07:36 UTC, miton18 commented on rollup.config.js
> +        // formiable (used by superagent) hijacks require :-(
typo ?

2024-10-14 07:36 UTC, miton18 commented on src/load-package-json.cjs
maybe later https://nodejs.org/dist/v18.15.0/docs/api/esm.html#esm_import_assertions

2024-10-14 07:48 UTC, miton18 commented
QA: Works on my side

2024-10-16 16:16 UTC, hsablonniere commented on rollup.config.js
> +        // formiable (used by superagent) hijacks require :-(
Good catch

2024-10-16 16:18 UTC, hsablonniere commented on src/load-package-json.cjs
Yes, except the syntax and name of the feature has changed, it's now the `with` keyword and Node unshipped the `assert` syntax.

https://nodejs.org/api/esm.html#import-attributes

We'll be able to go for v22 soon.

2024-10-16 16:26 UTC, merged