fix(update-notifier): set `isGlobal` to `true`
CleverCloud/clever-tools pull request #821
Opened 2024-09-06 07:05 UTC by florian-sanders-cc

Fixes #812

## What does this PR do?

This PR enables the `isGlobal` flag of the `update-notifier` as discussed with @davlgd.

The update message now rightfully specifies to use `npm i -g` instead of `npm i`
![usual clever tools update message specifying to use npm i -g clever-tools](https://github.com/user-attachments/assets/0f814b5c-91fc-4f8b-a9b5-c5dba1349c37)

2024-09-06 07:25 UTC, davlgd requested changes
LGTM, juste an URL change to add. 

To check it I edited the `package.json` version and added `updateCheckInterval: 0,` in `updateNotifierModule.notify()` as explained [here](https://github.com/yeoman/update-notifier/blob/HEAD/example.js)

Thanks @florian-sanders-cc for the link ^^

2024-09-06 07:25 UTC, davlgd commented on bin/clever.js
>        const docsUrl = 'https://www.clever-cloud.com/doc/clever-tools/getting_started';
```suggestion
      const docsUrl = 'https://github.com/CleverCloud/clever-tools/tree/master/docs#how-to-use-clever-tools';
```

2024-09-06 08:16 UTC, miton18 approved these changes

2024-09-11 16:34 UTC, hsablonniere approved these changes
Thank you @florian-sanders-cc for this and @davlgd @miton18 for the reviews!

2024-09-11 16:34 UTC, merged