docs(setup-systems): remove `Chocolatey` from Windows setup options
CleverCloud/clever-tools pull request #870
Opened 2024-12-19 17:26 UTC by florian-sanders-cc

Fixes #869

## What does this PR do?

- Removes `Chocolatey` from Windows setup options

The `chocolatey` package is outdated (`0.10.1` from 2018). 
We need to discuss if we want to maintain it there but in the meantime it would be better to simply remove this option from the setup docs.

2025-01-07 13:20 UTC, davlgd approved these changes

2025-02-26 14:43 UTC, hsablonniere requested changes
We discussed this at the last meeting because technically, we rely on Chocolatey the tool but the up to date nupkg is published on nexus and should still work for windows users.

@davlgd have you had time to check this?

2025-02-27 08:19 UTC, miton18 approved these changes

2025-03-05 17:14 UTC, hsablonniere commented
@davlgd I see, thanks for the investigation. Can you update the docs and we'll rollup our winget plan later :wink:

2025-03-05 17:39 UTC, merged